### Copy, View and Deep Copy

In [2]:
## View - Same object but reference changes

In [8]:
import numpy as np
a = np.arange(4)
b = a.view()
print(a)
print("------")
print(b)
b.shape = 2,2  ## changing the shape of b doesn't affect the shape of a 
print(b)
print("-------")
print(a)
print("--------")
print(b is a)  ## id is different

[0 1 2 3]
------
[0 1 2 3]
[[0 1]
 [2 3]]
-------
[0 1 2 3]
--------
False


In [10]:
### Deep copy - copies the object, array except the location
# Used when list of lists, complex data structures
## View does not work with compound data types
### View is used to copy the data without affecting it
### Difference between view and copy

### Broadcasting -- 
Arrays have 2 conditions: <br>
1. Either compatible arrays
2. Broadcasting


In [4]:
import numpy as np
p = np.array([1,2,3])
q = [4.0]
print(p+q)

[5. 6. 7.]


In [7]:
a = np.array([[0,0,0],[10,10,10],[20,20,20],[30,30,30]])
b = np.array([1,2,3])
print(a+b)

[[ 1  2  3]
 [11 12 13]
 [21 22 23]
 [31 32 33]]


### Linear Algebra

In [8]:
import numpy.matlib
import numpy as np

In [9]:
## dot product
## vector product
## inner product

In [10]:
## determinant
## inverse of a matrix 
## solve linear equations

In [18]:
a = np.array([[10,20],[30,40],[50,50]])
b = np.array([[5,6,3],[7,8,5]])  ## matrices should be compatible for multiplication .i.e 2by3 and 3by2
print(a)
print(b)
print(np.dot(a,b))
print("-----------")
print(np.vdot(a,b))

[[10 20]
 [30 40]
 [50 50]]
[[5 6 3]
 [7 8 5]]
[[190 220 130]
 [430 500 290]
 [600 700 400]]
-----------
1190


In [21]:
### solve system of equations 4*x0 + 3*x1 = 18  and x0 + 3 * x1 = 0:
a = np.array([[4,3],[1,3]])
b = np.array([18,9])
x = np.linalg.solve(a,b)  ## linalg
print(x)
## check that the solution is correct:
np.allclose(np.dot(a, x),b)  ## np.allclose- for precision, if the value comes non-terminating, hence to overcome that issue

[3. 2.]


True

In [23]:
# Solve the system of equtions 4 * x0 + 3x1 + x2 = 25, x0 + 3*x1 - x2 = 2, 2x0-x1=23
a = np.array([[4,3,1],[1,3,-1],[2,-1,-1]])  ### we have to enter the values manually,any function that does it
b = np.array([18,9,-3])
x = np.linalg.solve(a,b)
print(x)
np.allclose(np.dot(a,x),b)

[1.38461538 3.34615385 2.42307692]


True

## Matrix Library

In [28]:
# to generate matrices quickly
# np.empty_like(a) : Return an empty  array with shape and type of input
d_like: return an array of oneswith shape and type of input
# zeros_like: Retuurn an array of zeroes with shape and type of input
# full_like: 
# np.empty([2,2])
# ones:
# np.zeroes((2,),dtype=[('x','i4'),('y','i4')])
# np.zeros:
# np.full((2,2),np.inf): return a new array of givem shape filled with infinite

In [26]:
a = np.array([[1,2],[3,4],[5,6]])
print(np.empty_like(a))

[[          0  1077018624]
 [          0  1075970048]
 [          0 -1073217536]]
