### Array operations

In [2]:
import numpy as np
a = np.arange(9, dtype = np.float_).reshape(3,3)
b = np.arange(10,19,dtype = np.float_).reshape(3,3)
c = a + b
d = a - b
e = a*b
f = a/b
print(c)
print("---------")
print(d)
print("---------")
print(e)
print("---------")
print(f)
print("---------")

[[10. 12. 14.]
 [16. 18. 20.]
 [22. 24. 26.]]
---------
[[-10. -10. -10.]
 [-10. -10. -10.]
 [-10. -10. -10.]]
---------
[[  0.  11.  24.]
 [ 39.  56.  75.]
 [ 96. 119. 144.]]
---------
[[0.         0.09090909 0.16666667]
 [0.23076923 0.28571429 0.33333333]
 [0.375      0.41176471 0.44444444]]
---------


## np.reciprocal(a)

In [4]:
a = np.reciprocal(b)
print(a)

[[0.1        0.09090909 0.08333333]
 [0.07692308 0.07142857 0.06666667]
 [0.0625     0.05882353 0.05555556]]


## np.power(a,b)

In [7]:
pow = np.array([0,1,2,0,1,2,0,1,2]).reshape(3,3)
print(np.power(a,pow))
print("------")
print(np.remainder(a,pow))
print("------")
print(np.mod(a,pow))

[[1.         0.09090909 0.00694444]
 [1.         0.07142857 0.00444444]
 [1.         0.05882353 0.00308642]]
------
[[       nan 0.09090909 0.08333333]
 [       nan 0.07142857 0.06666667]
 [       nan 0.05882353 0.05555556]]
------
[[       nan 0.09090909 0.08333333]
 [       nan 0.07142857 0.06666667]
 [       nan 0.05882353 0.05555556]]


C:\Users\HP\Anaconda3\lib\site-packages\ipykernel_launcher.py:4: RuntimeWarning: invalid value encountered in remainder
  after removing the cwd from sys.path.
C:\Users\HP\Anaconda3\lib\site-packages\ipykernel_launcher.py:6: RuntimeWarning: invalid value encountered in remainder
  


### Trignometric and complex functions
1. np.sin(a*np.pi/180) #includes conersion to radians
2. np.cos(a*np.pi/180)
3. np.tan(a*np.pi/180)
4. inv = np.arcsin(sin) inverse(arcsin) of sin
5. np.degrees(inv) converts inverse in radians to degrees
6. ROUND, CEIL, FLOOR
7. numpy.around(a,decimals) rounds to the desired precisiom


In [10]:
a = np.array([-1.7, 1.5, -0.2, 0.6, 10])
print(np.floor(a))
print(np.ceil(a))

[-2.  1. -1.  0. 10.]
[-1.  2. -0.  1. 10.]


## Copy, View and Deep Copy

In [11]:
## Note: everything in Python is an object, even numbers and Classes
# Python uses 3 concepts: copy, view and deep copy for operations
# A simple assignment does not make the copy of an array object
# Instead, it uses the same id() of the original array to access it
# Compound objects are those that contain other objects, like lists or class instances

In [19]:
a = np.arange(4)
print(id(5))
print(a)
print(id(a))
b = a
print(b)
x = id(a)
y = id(b)
print(y)
b.shape = 2,2
print(b)  ## The shape of b is changed
print(a)  ## Shape of a also gets changed to b
print(b is a) ## Thus a and b are pointing to the same memory location, 
## This b is NOT a copy of a

1394764992
[0 1 2 3]
2109108806240
[0 1 2 3]
2109108806240
[[0 1]
 [2 3]]
[[0 1]
 [2 3]]
True
