In [2]:
import numpy as np

### iscomplex() 
returns only the complex values from the array

In [6]:
a = np.array([1,2+6j,5,3.5+5j,2])
print(a[np.iscomplex(a)]) ##  iscomplex()

[2. +6.j 3.5+5.j]


### NaN values
isnan()

In [8]:
a = np.array([np.nan, 1,2, np.nan,3,4,5])
print(a)
print("---------------------------")
print(a[~np.isnan(a)]) ##   negation of isnan()

[nan  1.  2. nan  3.  4.  5.]
---------------------------
[1. 2. 3. 4. 5.]


### Iterating, Copying, Searching and Sorting

### Transpose of the Array

In [9]:
a = np.arange(0,120,10).reshape(3,4) ### chaining
print(a)
print("----------------")

for x in np.nditer(a):  ## iteration
    print(x)

print("----------------")
print("Transpose of the original array: \n",a.T) ### Transpose - .T


[[  0  10  20  30]
 [ 40  50  60  70]
 [ 80  90 100 110]]
----------------
0
10
20
30
40
50
60
70
80
90
100
110
----------------
Transpose of the original array: 
 [[  0  40  80]
 [ 10  50  90]
 [ 20  60 100]
 [ 30  70 110]]


### Diff in C and Fortran Styles
C - C
F - Fortran

In [10]:
print(a)
print("----------------")
b = a.copy(order = 'C')

for x in np.nditer(b):
    print(x)
print("----------------")


c = a.copy(order = 'F')
for x in np.nditer(c):
    print(x)

[[  0  10  20  30]
 [ 40  50  60  70]
 [ 80  90 100 110]]
----------------
0
10
20
30
40
50
60
70
80
90
100
110
----------------
0
40
80
10
50
90
20
60
100
30
70
110


### flags operator -- > readonly, writeonly, readwrite

In [11]:
for x in np.nditer(a, op_flags=['writeonly']):  ## value will not be read, only displayed/written
    x[...] = 2*x
print(a)

[[  0  20  40  60]
 [ 80 100 120 140]
 [160 180 200 220]]


In [12]:
for x in np.nditer(a, op_flags=['readonly']): ### will give an error as the value can not be written
    x[...] = 2*x
print(a)

ValueError: assignment destination is read-only

In [13]:
for x in np.nditer(a, op_flags=['readwrite']):  ## can both read and write(by default)
    x[...] = 2*x
print(a)

[[  0  40  80 120]
 [160 200 240 280]
 [320 360 400 440]]


### External Loop

In [14]:
for x in np.nditer(a, flags=['external_loop'],order='F'):  ##external loop - slices only column
    print(x)
    
print("---------------------")

for x in np.nditer(a, flags=['external_loop'],order='C'): ## value willbe displayed in a list manner
    print(x)

[  0 160 320]
[ 40 200 360]
[ 80 240 400]
[120 280 440]
---------------------
[  0  40  80 120 160 200 240 280 320 360 400 440]


### Sorting - np.sort()

numpy.sort(a, axis, kind, order)
kind - quicksort, mergesort(depriciated), heapsort

In [16]:
b = np.random.randint(8, size=(2,4)) ### random array,         ### random sampling
b
print(np.sort(b, axis=1))  ## 1 - Rows, 0 - Columns, by default 1(Row)

print("----------------")

print(np.sort(b, axis=0))

#### sorting by name

[[1 3 5 7]
 [2 3 3 3]]
----------------
[[3 3 3 1]
 [5 3 7 2]]


### indirect sort functions

In [26]:
### OCR - Object Character Recognition

In [19]:
# numpy.argsort()
# numpy.lexsort()  ## calculates indicis first

fn = ('pitter','chavi','kaju','roverg' )
cl = ('t.y.','f.y.','f.y.','s.y.') ## third year, second year, third year
ind = np.lexsort((cl,fn)) ## will be sorted by names - last one entered

print(ind)
print([fn[i] +", " + cl[i] for i in ind])  ## sorted by names

[1 2 0 3]
['chavi, f.y.', 'kaju, f.y.', 'pitter, t.y.', 'roverg, s.y.']


In [42]:
## numpy.argmax()  ## they return the indicis for max and min
## numpy.argmin()
b = []
indexMax = np.argmax(a, axis = 0)
indexMin = np.argmin(a, axis=1) 

print(a)
print(indexMax)

[[  0  40  80 120]
 [160 200 240 280]
 [320 360 400 440]]
[2 2 2 2]


##### np.nonzero(a)  ---> To check non-zero elements

#### Searching specifically for an element

In [21]:
result = np.where(x==440)
print(result)

(array([11], dtype=int64),)


##### Extracting elelemts given a certain condition

In [22]:
a = np.arange(12).reshape(3,4)
print(a)
print("-------------------------")
conditn = np.mod(a,2) == 0 ## condition specified
print(conditn)
print("-------------------------")
print(np.extract(conditn,a))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
-------------------------
[[ True False  True False]
 [ True False  True False]
 [ True False  True False]]
-------------------------
[ 0  2  4  6  8 10]
