### 3 types of indexing methods 
remember all types of indexing

field access, basic access, advanced access

In [6]:
## slice object
import numpy as np
a = np.arange(10)
s = slice(2,7,2) ## start, stop, step
b = a[2:7:2]
c = a[5]
print(a[2:5])
print("-----------")
print(a[2:])
print("-----------")
print(c)
print("-----------")
print(a[s], b)

[2 3 4]
-----------
[2 3 4 5 6 7 8 9]
-----------
5
-----------
[2 4 6] [2 4 6]


In [12]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a)
print("------------")
print(a[1:]) 
print("------------")
print(a[:1])        ## 0th row
print("------------")
print(a[0,0])
print("------------")
print(a[2,2])
print("------------")
print(a[0:,0:]) 

[[1 2 3]
 [4 5 6]
 [7 8 9]]
------------
[[4 5 6]
 [7 8 9]]
------------
[[1 2 3]]
------------
1
------------
9
------------
[[1 2 3]
 [4 5 6]
 [7 8 9]]


### Ellipsis 
3 dots ... --> Provides a tuple, when used at a row position, it will return the entire row

In [34]:
a = np.array([[1,2,3],[3,4,5],[5,6,7]])
print(a)
print("------------")
print(a[...,1]) ### No row specified, column 2 understood by default
print("--------------")
print(a[1,...])
print("--------------")
print(a[...,1:])

[[1 2 3]
 [3 4 5]
 [5 6 7]]
------------
[2 4 6]
--------------
[3 4 5]
--------------
[[2 3]
 [4 5]
 [6 7]]


### Integer Indexing

In [38]:
x = np.array([[1,2], [3,4], [5,6]])
y = x[[0,1,2], [0,1,0]] ## r0c0, r1c1, r2c0
z = x[[2,0,1],[1,1,1]]
print(x)
print("-----------")
print(y)
print("-----------")
print(z)
print("-----------")
## works like a matrix


[[1 2]
 [3 4]
 [5 6]]
-----------
[1 4 5]
-----------
[6 2 4]
-----------


### Field Indexing

In [46]:
## explicitely declare dtypes
x = np.array([('Rex',9,81.0), ('Fido',3,27.0)], 
             dtype=[('name','U2'),('age','i4'),('weight','f4')]) ### explicitly specify the length of the word "Rex"
a = x[0] #create a slice and assign it to a new variable
print(a)
print("-----------")
print(x['name'])
print("-----------")
print(x['age'])
print("-----------")
y = x['age']
print(y)
print("-----------")
print(y>5) ## returns boolean, returns true or false


('Re', 9, 81.)
-----------
['Re' 'Fi']
-----------
[9 3]
-----------
[9 3]
-----------
[ True False]


### Integer Indexing, example 2

In [54]:
x = np.array([[0,1,2],[3,4,5],[6,7,8],[9,10,11]])
print(x)
print("-----------")
print(x[0,0])
print("-----------")
p = x[[0,0],[0,2]]
r = x[[0,0], [0,2]]  ## why out of bounds
print(p)
print("-----------")
print(r)
print("-----------")


[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
-----------
0
-----------
[0 2]
-----------
[0 2]
-----------
