In [5]:
import numpy as np
x = np.array([[0,1,2,12],[3,4,5,13],[6,7,8,14],[9,10,11,15]])
p2 = x[x[1,0],[1,2]]
p2

array([10, 11])

In [6]:
### out of bounds error
p2 = x[x[3,0],[3,1]]

IndexError: index 9 is out of bounds for axis 0 with size 4

### Slicing and selecting 

In [9]:
x = np.array([[0,1,2],[3,4,5],[6,7,8],[9,10,11]])
a = x[2:]
a0 = x[:1]
a0c1 = x[0:2]
a0c2 = x[0:1]

print(a)
print("----------")
print(a0)
print("----------")
print(a0c1)
print("----------")
print(a0c2)

[[ 6  7  8]
 [ 9 10 11]]
----------
[[0 1 2]]
----------
[[0 1 2]
 [3 4 5]]
----------
[[0 1 2]]


In [11]:
a1 = x[2:,1:]
a2 = x[2:,2:]
a3prior = x[0:2]
a3 = x[0:2,0:1]
a4 = x[1:3,0:1]
print(a1)
print("----------")
print(a2)
print("----------")
print(a3)
print("----------")

[[ 7  8]
 [10 11]]
----------
[[ 8]
 [11]]
----------
[[0]
 [3]]
----------
[[3]
 [6]]


In [18]:
## advanced slicing

## Boolean Indexing with Numpy 
<a href = "https://docs.scipy.org/doc/numpy/reference/routines.logic.html">Boolean Documentation </a>