### Complex numbers using Matrix
using zip to remove the complex numbers in a for loop in a mtrix

In [88]:
[complex(a,b) for a,b in zip([1,2,3],[6,2,3])] ##zip use ---> to combine 2 values and the result is in the form of a tuple

[(1+6j), (2+2j), (3+3j)]

In [89]:
numbers = [1, 2, 3]
letters = ['a', 'b', 'c']
zipped = list(zip(numbers, letters))
zipped

a = [1,2,3]
b = [6,2,3]
zipped = list(zip(a,b))
print(zipped)  ##to zip 2 matrices

[(1, 6), (2, 2), (3, 3)]


### Shaping an array explicitely


In [92]:
## u can also shape an array explicitely
import numpy as np
matrix1 = np.array([[1,2,3],[4,5,6]])
print(matrix1) ### before shaping explicitely, shape=2,3
print() 
matrix1.shape = (3,2)
print(matrix1.shape)
print(matrix1) ### after shaping explicitely, shape=3,2

[[1 2 3]
 [4 5 6]]

(3, 2)
[[1 2]
 [3 4]
 [5 6]]


### Difference between shape and reshape
Shape to give shape to already existing array and to the same array/matrix <br>
Reshape is to shape the array and assign it to a new matrix 

### Ndim method

In [102]:
matrix1 = np.array([[1,2,3],[4,5,6],[5,6,7]])
matrix2 = np.array([[[1,2,3],[7,8,9],[7,8,9]]])


print(matrix1.ndim)  ## returns dimesnions
print(matrix2.shape)
print(matrix2.ndim)

2
(1, 3, 3)
3


In [105]:
a = np.array([[1,2,3,4,5,6],[1,2,4,5,6,3]], ndmin=4)
print(a)
print(a.ndim)
print(a.shape)

[[[[1 2 3 4 5 6]
   [1 2 4 5 6 3]]]]
4
(1, 1, 2, 6)


### arange function
Creates a vector starting from zero till value mentioned - 1

In [106]:
a = np.arange(24) ##[0,24)
print(a) ##1darray

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


### exploration -
understanding dimesnions, details, dtypes etc etc

### reshape function

In [22]:
b = a.reshape(2,4,3)
print(b) ### 3darray

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]]


### itemsize

In [109]:
matrix1 = np.array([1,2,3], dtype=float)
print(matrix1.itemsize)   ## no of bytes each item in the vector has

8


In [110]:
x = np.array([1,2,3,4,5], dtype=np.float32)
print(x.itemsize)

4


hw -  do for every single datatypes -16-18. To see how much each item take
### Datatypes in np
1. bool_
2. int_
3. intc
4. intp
5. int8
5. int16
6. int32
7. int64
8. uint8
9. uint16
10. uint32
11. uint64
12. float_
13. float16
14. float32
15. float64
16. complex_
17. complex64
18. complex128

In [120]:
matrix1 = np.array([1,2,3,4], dtype=np.bool_)
print("Bool: ",matrix1.itemsize)

matrix1 = np.array([1,2,3,4], dtype=np.int_)
print("Int: ",matrix1.itemsize)

matrix1 = np.array([1,2,3,4], dtype=np.intc)
print("Intc: ",matrix1.itemsize)

matrix1 = np.array([1,2,3,4], dtype=np.intp)
print("Intp: ",matrix1.itemsize)

matrix1 = np.array([1,2,3,4], dtype=np.int8)
print("Int8: ",matrix1.itemsize)

matrix1 = np.array([1,2,3,4], dtype=np.int16)
print("Int16: ",matrix1.itemsize)

matrix1 = np.array([1,2,3,4], dtype=np.int32)
print("Int32: ",matrix1.itemsize)

matrix1 = np.array([1,2,3,4], dtype=np.int64)
print("int64: ",matrix1.itemsize)

matrix1 = np.array([1,2,3,4], dtype=np.uint8)
print("Uint8: ",matrix1.itemsize)

matrix1 = np.array([1,2,3,4], dtype=np.uint16)
print("Uint16: ",matrix1.itemsize)

matrix1 = np.array([1,2,3,4], dtype=np.uint32)
print("Uint32: ",matrix1.itemsize)

matrix1 = np.array([1,2,3,4], dtype=np.uint64)
print("Unit64: ",matrix1.itemsize)

matrix1 = np.array([1,2,3,4], dtype=np.float_)
print("Float: ",matrix1.itemsize)

matrix1 = np.array([1,2,3,4], dtype=np.float16)
print("Float16: ",matrix1.itemsize)

matrix1 = np.array([1,2,3,4], dtype=np.float32)
print("Float32: ",matrix1.itemsize)

matrix1 = np.array([1,2,3,4], dtype=np.float64)
print("Float64: ",matrix1.itemsize)

matrix1 = np.array([1,2,3,4], dtype=np.complex_)
print("Complex_: ",matrix1.itemsize)

matrix1 = np.array([1,2,3,4], dtype=np.complex64)
print("Complex64: ",matrix1.itemsize)

matrix1 = np.array([1,2,3,4], dtype=np.complex128)
print("Complex128: ",matrix1.itemsize)

Bool:  1
Int:  4
Intc:  4
Intp:  8
Int8:  1
Int16:  2
Int32:  4
int64:  8
Uint8:  1
Uint16:  2
Uint32:  4
Unit64:  8
Float:  8
Float16:  2
Float32:  4
Float64:  8
Complex_:  16
Complex64:  8
Complex128:  16


### Flag Attributes

In [27]:
x = np.array([1,2,3,4,5])
print(x.flags)   
## Are these compatible is with C and Fortran
## Owndata - Source related (Kya ye mene khud generate kiya hai)
### Writeable - > We can change it or not
### Writebackifcopy --> upstream and downstream* programming, agar kisi ne parent/master data change kiya hai, it will come back and hnage this data also
#### UpdateifCopy

  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False


### ASARRAY function

In [121]:
## Convert existing data into numpy array
## when to use it...
x=[1,2,3]
a = np.asarray(x)
print(a)
print(type(a))
##diff between array and asarray function
## np.asarray will change the original matrix/array as well

[1 2 3]
<class 'numpy.ndarray'>


In [41]:
## ndarray from tuple
a = 1,2,3  ##tuple hw. what and why
b = (4,5,6)
m1 = np.asarray(a)
m2 = np.asarray(b)
print(a)
print(b)
print(m1,m2)



(1, 2, 3)
(4, 5, 6)
[1 2 3] [4 5 6]


In [49]:
## ndarray from list of tuples
x = [(1,2,3),(4,5)]
a = np.asarray(x)
print(a)
print(type(a))
print(a.shape)
x = np.array([1,2,3])
print(x.shape)
print(x)

[(1, 2, 3) (4, 5)]
<class 'numpy.ndarray'>
(2,)
(3,)
[1 2 3]


# DOUBT

In [126]:


##numpy.frombuffer(buffer, dtpe=float, count=-1, offset=0)
## used to create a vector from a specified buffer
import numpy as np  
l = b'hello world'  
print(type(l))  
a = np.frombuffer(l, dtype = "S1")  
print(a)  
print(type(a))  


##numpy.fromiter
iterable = (x*x for x in range(5))
np.fromiter(iterable, float)
np.array([  0.,   1.,   4.,   9.,  16.])



<class 'bytes'>
[b'h' b'e' b'l' b'l' b'o' b' ' b'w' b'o' b'r' b'l' b'd']
<class 'numpy.ndarray'>


array([ 0.,  1.,  4.,  9., 16.])

In [55]:
## numpy.arange(start, stop, step, dtype)

In [57]:
x= np.arange(3,15,.2,float)
print(x)

[ 3.   3.2  3.4  3.6  3.8  4.   4.2  4.4  4.6  4.8  5.   5.2  5.4  5.6
  5.8  6.   6.2  6.4  6.6  6.8  7.   7.2  7.4  7.6  7.8  8.   8.2  8.4
  8.6  8.8  9.   9.2  9.4  9.6  9.8 10.  10.2 10.4 10.6 10.8 11.  11.2
 11.4 11.6 11.8 12.  12.2 12.4 12.6 12.8 13.  13.2 13.4 13.6 13.8 14.
 14.2 14.4 14.6 14.8]


### Numpy.linspace

In [65]:
x = np.linspace(10,20,5) ## number of evenly spaced samples, by default 50
print(x) 
## inclides both the end points

[10.  12.5 15.  17.5 20. ]


In [70]:
y = np.linspace(10,30,5, endpoint=False)  ## to exclude the end point
print(y)
print(type(y))

[10. 14. 18. 22. 26.]
<class 'numpy.ndarray'>


In [79]:
y = np.linspace(1,2,5, retstep=True) ##return step
print(y)
print(type(y))
### showing tuple, write to the documentation

(array([1.  , 1.25, 1.5 , 1.75, 2.  ]), 0.25)
<class 'tuple'>


# DOUBT

In [73]:
## logs - > 

In [76]:
### numpy.logspace(start, stop, num, endpoint, base, dtype)
## AP GP

## default base is 10
a = np.logspace(1.0, 3.0, num=10) 
## Set base of log space to 2

b = np.logspace(1,10, num=8, base=2)
print(a)
print("----------------------------")
print(b)

[  10.           16.68100537   27.82559402   46.41588834   77.42636827
  129.1549665   215.443469    359.38136638  599.48425032 1000.        ]
----------------------------
[   2.            4.87605462   11.88795431   28.98315726   70.66172888
  172.27522466  420.01170228 1024.        ]


In [127]:
import math
## for finding logs
## read about logs and properties