# Numpy

''' Why no multiline comment in Python? Coz it is an interpreted language'''

'''Why numpy '''  For mdarray

In [0]:
import numpy as np
twod_array = np.array([[1,2],[2,4]]) ##2d array
twod_array

array([[1, 2],
       [2, 4]])

In [0]:
three_darray = np.array([[1,2],[3,4]], ndmin=3) ##ndmin here 3 dim array
print(three_darray)

[[[1 2]
  [3 4]]]


In [0]:
### What is ndmin 

In [0]:
three_darray = np.array([1,2,3,4,5], ndmin=3)
print(three_darray)

[[[1 2 3 4 5]]]


In [0]:
### complex datatypes in numpy

In [0]:
### complex no as a matrix

In [0]:
#### datatypes numpy supports

In [0]:
array1 = np.array([[1,2,3],[2,3,4]],dtype="complex")

In [0]:
array1

array([[1.+0.j, 2.+0.j, 3.+0.j],
       [2.+0.j, 3.+0.j, 4.+0.j]])

In [0]:
### shape 
array1.shape

(2, 3)

In [0]:
### Operations in Numpy